# mysql connect configuration
mysql:
  username: wcx
  password: 'Ghy123456.'
  path: '112.35.65.76:3306'
  db-name: 'manager'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true

# jwt configuration
jwt:
  signing-key: 'qmPlus'
# system configuration
system:
  use-multipoint: false
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888

# logger configuration
log:
  prefix: '[BLOG]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

# captcha configuration
captcha:
  key-long: 4
  img-width: 240
  img-height: 80
