# mysql connect configuration
# password: 'Ghy123456.'
#  path: '112.35.65.76:3306'
mysql:
  username: 'root'
  password: 'Wcx950222...'
  path: '1.116.155.18:3306'
  #username: 'root'
  #password: '123456'
  #path: '127.0.0.1:3306'
  db-name: 'blog'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true
  log-zap: ""

# jwt configuration
jwt:
  signing-key: 'blog'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false

# logger configuration
log:
  prefix: '[BLOG]'
  log-file: true
  stdout: 'DEBUG'
  file: 'DEBUG'

# captcha configuration
captcha:
  key-long: 4
  img-width: 240
  img-height: 80

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[BLOG]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

tencent-cos:
  bucket: 'blogstore-1301375948'
  region: 'ap-nanjing'
  secret-id: 'AKIDGJ7PSFxY7PSEAqKKApFPJUP4Tax4uToK'
  secret-key: 'PYhGsELAvmNmvo25t24EBzcy5uRIEyXN'
  base-url: 'https://store.wuchangxin.club'
